#!/bin/bash
ssh ubuntu@52.79.73.181 <<EOF
    cd ~/mohae-back/mohae
    git pull origin develop
    curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
    . ~/.nvm/nvm.sh
    sudo nvm install 16.2.0
    sudo npm install
    sudo npm install -g typescript
    sudo npm install -g ts-node
    sudo npm install -g pm2
    pm2 install typescript
    pm2 restart ecosystem.config.js
    exit
EOF